name: Testing on pull request

on:
  pull_request:
    branches: [main, master]

jobs:
  preparing:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake
  
  build:
    needs: preparing
    runs-on: ubuntu-latest

    steps:
    # Важно: повторить checkout в каждом job, где нужен код
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure project
      run: |
        cmake -B build -S .

    - name: Build project and tests
      run: |
        cmake --build build --parallel $(nproc)

  testing:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run all tests
      run: |
        cd  && ctest --output-on-failure